name: Test script 
on:
    push:
        branches:
            -main 
jobs:
    extract-job:
        runs-on: ubunatu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: print message
              run: echo "Hello world"
              
