name: ETL Workflow
on:
    push:
        branches:
        - main
jobs:
    extract_job:    
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run ETL script
          run: python extract.py

    transform_job:
        runs-on: ubuntu-latest
        needs: extract_job
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run ETL script
          run: python transform.py
          
    load_job:
        runs-on: ubuntu-latest
        needs: transform_job
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run ETL script
          run: python load.py
            
            

